export const createMockUser = (overrides: any = {}) => ({
  id: '1',
  email: 'test@test.com',
  name: 'Test User',
  password: 'hashed',
  role: 'user',
  isRootAdmin: false,
  emailVerified: new Date(),
  image: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  status: 'active',
  suspendedAt: null,
  deletedAt: null,
  stripeCustomerId: null,
  ...overrides,
})
